### ISSUE TITLE
Touch spells bug

### ISSUE THREAD

**Issue by TontoBuzz** [Daenks/Meridian59_103#424] opened 2014-04-09 12:01 UTC
Randomly, the touch spell stops to work and each time the attack key is pressed, mana goes down by 10.
A recast of the same spell will not resolve the issue, but casting another touch spell then back the spell will resolve the issue:

Cast the spell, then here is what happens when the attack key is pressed:

Your hands no longer drip with acidic ooze.
The corrosive spittle of Qor's love oozes from the pores of your hand.
Your hands no longer drip with acidic ooze.
The corrosive spittle of Qor's love oozes from the pores of your hand.
The living tree's attack nicks you for 1 damage.
Your hands no longer drip with acidic ooze.
The corrosive spittle of Qor's love oozes from the pores of your hand.
Your hands no longer drip with acidic ooze.
The corrosive spittle of Qor's love oozes from the pores of your hand.
Your hands no longer drip with acidic ooze.
The corrosive spittle of Qor's love oozes from the pores of your hand.
Your hands no longer drip with acidic ooze.
The corrosive spittle of Qor's love oozes from the pores of your hand.
Your hands no longer drip with acidic ooze.
The corrosive spittle of Qor's love oozes from the pores of your hand.
Your hands no longer drip with acidic ooze.
The corrosive spittle of Qor's love oozes from the pores of your hand.
The living tree's attack nicks you for 1 damage.
You don't have enough mana to cast acid touch!
Your hands no longer drip with acidic ooze.
Sparks jump and crackle from your fingertips.
The giant rat's attack claws you for 1 damage.
The giant rat's attack claws you for 1 damage.
System is saving; please wait.
System save completed; resume play.
### Your safety is now ON:  You can no longer strike innocents.
The living tree's attack nicks you for 2 damage.
Your zap shocks the living tree for 15 damage.
The living tree is slightly wounded.
Your zap shocks the living tree for 13 damage.
The living tree is clearly injured.
Your zap shocks the living tree for 13 damage.
The living tree is seriously wounded.
The living tree's attack nicks you for 1 damage.
Your fingers are no longer charged with electrical power.
The corrosive spittle of Qor's love oozes from the pores of your hand.
Your acid touch sears the living tree for 11 damage.
The living tree is weak, and near death.

**Comment by skittles1** [comment] 2015-07-26 01:24
Still unable to reproduce, closing.

**Closed by skittles1** 2015-07-26 01:24 UTC
